version: '3'

services:
  mongo:
    image: mongo:4.2.23-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  express-identity-server:
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: production
      SERVER_PROTOCOL: http
      SERVER_PORT: '3000'
      SERVER_HOST: '0.0.0.0'
      SERVER_PUBLIC_DIRECTORY: public
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: stuff
      DATABASE_USER: root
      DATABASE_PASSWORD: example
